DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  fullName TEXT NOT NULL,
  bio TEXT NOT NULL,
  avatar TEXT NOT NULL,
  email TEXT NOT NULL,
  passwordHash TEXT NOT NULL,
  verified INTEGER DEFAULT 0 CHECK(verified IN (0, 1))
);